# Generated by Django 4.1.7 on 2023-04-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vmoney',
            field=models.IntegerField(default=0, verbose_name='Деньги'),
        ),
    ]
