# Generated by Django 4.1.7 on 2023-04-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_customuser_vmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Обращение к пользователю'),
        ),
    ]
