# Generated by Django 4.1.7 on 2023-05-09 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_customuser_is_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Заказ')),
                ('member1', models.CharField(default='', max_length=255, verbose_name='Участник 1')),
                ('member2', models.CharField(default='', max_length=255, verbose_name='Участник 2')),
            ],
            options={
                'verbose_name': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.IntegerField(default=0, verbose_name='Id чата')),
                ('message', models.TextField(default='', max_length=500, verbose_name='Сообщение')),
                ('sender', models.CharField(default='', max_length=255, verbose_name='Отправитель')),
                ('sendertype', models.CharField(default='', max_length=255, verbose_name='Тип отправителя')),
                ('reciever', models.CharField(default='', max_length=255, verbose_name='Получатель')),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 5, 9, 20, 59, 50, 521195), verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
