# Generated by Django 4.1.7 on 2023-05-09 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_chats_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 21, 7, 57, 606455), verbose_name='Последнее сообщение'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 21, 7, 57, 607511), verbose_name='Время'),
        ),
    ]
