# Generated by Django 4.1.7 on 2023-05-09 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_rename_member2_chats_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chats',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AddField(
            model_name='chats',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Описание чата'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 21, 18, 59, 625130), verbose_name='Последнее сообщение'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 21, 18, 59, 626107), verbose_name='Время'),
        ),
    ]
