# Generated by Django 4.1.7 on 2023-05-09 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_chats_options_chats_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='client',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='chats',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 22, 56, 10, 177029), verbose_name='Последнее сообщение'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 22, 56, 10, 177029), verbose_name='Время'),
        ),
    ]
