# Generated by Django 4.1.7 on 2023-05-10 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_remove_chats_order_alter_chats_last_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='worker',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='chats',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='reciever',
            new_name='receiver',
        ),
        migrations.AlterField(
            model_name='chats',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 23, 2, 20, 399070), verbose_name='Последнее сообщение'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 23, 2, 20, 400071), verbose_name='Время'),
        ),
    ]
