# Generated by Django 4.1.7 on 2023-05-10 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_rename_worker_chats_staff_rename_customer_chats_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.IntegerField(default=0, verbose_name='Id чата')),
                ('message', models.TextField(default='', max_length=500, verbose_name='Сообщение')),
                ('sender', models.CharField(default='', max_length=255, verbose_name='Отправитель')),
                ('sendertype', models.CharField(default='', max_length=255, verbose_name='Тип отправителя')),
                ('receiver', models.CharField(default='', max_length=255, verbose_name='Получатель')),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 5, 10, 23, 13, 4, 873454), verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.AlterField(
            model_name='chats',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 23, 13, 4, 871941), verbose_name='Последнее сообщение'),
        ),
    ]
