# Generated by Django 4.1.7 on 2023-05-10 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_alter_chatmessages_time_alter_chats_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 23, 31, 23, 704029), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 23, 31, 23, 705047), verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 23, 31, 23, 704029), verbose_name='Последнее сообщение'),
        ),
    ]
