# Generated by Django 4.1.7 on 2023-05-10 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_alter_chatmessages_time_alter_chats_last_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 23, 35, 4, 643252), verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 23, 35, 4, 642294), verbose_name='Последнее сообщение'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='time_created',
            field=models.DateField(default=datetime.datetime(2023, 5, 10, 23, 35, 4, 642294), verbose_name='Дата создания'),
        ),
    ]
