# Generated by Django 4.1.7 on 2023-05-11 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_alter_chatmessages_time_alter_chats_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 22, 41, 10, 839554), verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 22, 41, 10, 838555), verbose_name='Последнее сообщение'),
        ),
    ]
