# Generated by Django 4.1.7 on 2023-05-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_alter_chatmessages_time_alter_chats_last_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessages',
        ),
        migrations.DeleteModel(
            name='Chats',
        ),
    ]
