# Generated by Django 4.1.7 on 2023-04-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='Описание в услугах')),
                ('fulldesc', models.TextField(default='', verbose_name='Описание в окне')),
                ('cost', models.IntegerField(verbose_name='Минимальная цена')),
            ],
        ),
    ]
