# Generated by Django 4.1.7 on 2023-04-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказы'},
        ),
        migrations.AddField(
            model_name='orders',
            name='language',
            field=models.CharField(default='', max_length=255, verbose_name='Язык программирования'),
        ),
    ]
