# Generated by Django 4.1.7 on 2023-04-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orders_options_rename_language_orders_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='mincost',
            field=models.CharField(max_length=255, verbose_name='Минимальная цена'),
        ),
    ]
