# Generated by Django 4.1.7 on 2023-04-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orders_mincost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='mincost',
            field=models.IntegerField(verbose_name='Минимальная цена'),
        ),
    ]
