# Generated by Django 4.1.7 on 2023-04-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orders_mincost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('lang', models.CharField(default='', max_length=255, verbose_name='Язык программирования')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='Описание в услугах')),
                ('fulldesc', models.TextField(blank=True, verbose_name='Описание в окне')),
                ('mincost', models.IntegerField(verbose_name='Минимальная цена')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
            },
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.RemoveField(
            model_name='orders',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='fulldesc',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='mincost',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='title',
        ),
        migrations.AddField(
            model_name='orders',
            name='additional',
            field=models.TextField(default='', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='orders',
            name='service_id',
            field=models.IntegerField(default=0, verbose_name='ID услуги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='Запросившый услугу'),
        ),
        migrations.AddField(
            model_name='orders',
            name='worker',
            field=models.CharField(default='', max_length=255, verbose_name='Работающий над проектом'),
        ),
    ]
