# Generated by Django 4.1.7 on 2023-04-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_services_alter_orders_options_remove_orders_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='service_id',
            field=models.IntegerField(default=0, verbose_name='ID услуги'),
        ),
    ]
