# Generated by Django 4.1.7 on 2023-05-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orders_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Минимальная цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='additional',
            field=models.TextField(default='', verbose_name='Описание задания'),
        ),
    ]
