# Generated by Django 4.1.7 on 2023-05-03 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orders_cost_orders_title_alter_orders_additional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='', verbose_name='Сообщение')),
                ('sender', models.CharField(default='', max_length=255, verbose_name='Отправитель')),
                ('reciever', models.CharField(default='', max_length=255, verbose_name='Получатель')),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 5, 3, 11, 29, 58, 87735), verbose_name='Время')),
            ],
        ),
    ]
