# Generated by Django 4.1.7 on 2023-05-03 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_chats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chats',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AddField(
            model_name='chats',
            name='order_id',
            field=models.IntegerField(default=0, verbose_name='Id заказа'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='message',
            field=models.TextField(default='', max_length=500, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 13, 36, 41, 642474), verbose_name='Время'),
        ),
    ]
