# Generated by Django 4.2 on 2023-05-04 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_chats_options_chats_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='sendertype',
            field=models.CharField(default='', max_length=255, verbose_name='Тип отправителя'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 18, 50, 57, 292360), verbose_name='Время'),
        ),
    ]
