# Generated by Django 4.1.7 on 2023-05-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_delete_chats_rename_service_id_orders_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='username',
            new_name='user',
        ),
    ]
