# Generated by Django 4.1.7 on 2023-05-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_orders_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='worker',
            new_name='staff',
        ),
    ]
