# Generated by Django 4.1.7 on 2023-05-10 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_rename_worker_orders_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 23, 29, 44, 276212), verbose_name='Дата создания'),
        ),
    ]
