# Generated by Django 4.1.7 on 2023-05-10 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_orders_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 23, 31, 23, 708328), verbose_name='Дата создания'),
        ),
    ]
