# Generated by Django 4.1.7 on 2023-05-10 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_orders_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time_created',
            field=models.DateField(default=datetime.datetime(2023, 5, 10, 23, 32, 19, 3309), verbose_name='Дата создания'),
        ),
    ]
