# Generated by Django 4.1.7 on 2023-05-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_orders_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
