# Generated by Django 4.1.7 on 2023-05-11 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_orders_time_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.IntegerField(default=0, verbose_name='Id чата')),
                ('message', models.TextField(default='', max_length=500, verbose_name='Сообщение')),
                ('sender', models.CharField(default='', max_length=255, verbose_name='Отправитель')),
                ('sendertype', models.CharField(default='', max_length=255, verbose_name='Тип отправителя')),
                ('receiver', models.CharField(default='', max_length=255, verbose_name='Получатель')),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 5, 11, 22, 47, 2, 242563), verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Описание чата')),
                ('staff', models.CharField(default='', max_length=255, verbose_name='Участник 1')),
                ('user', models.CharField(default='', max_length=255, verbose_name='Участник 2')),
                ('time_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_message', models.DateTimeField(default=datetime.datetime(2023, 5, 11, 22, 47, 2, 241562), verbose_name='Последнее сообщение')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
    ]
